module.exports = {
  STRESS: {
    LOW: { min: 0, max: 20, label: 'low' },
    MODERATE: { min: 21, max: 50, label: 'moderate' },
    HIGH: { min: 51, max: 80, label: 'high' },
    CRITICAL: { min: 81, max: 100, label: 'critical' },
  },
  STRESS_LEVEL: {
    LOW: 'low',
    MODERATE: 'moderate',
    HIGH: 'high',
    CRITICAL: 'critical',
  },
  ACTIONS: {
    NONE: 'none',
    BREATHING: 'breathing',
    AUDIO: 'audio',
    RESET: 'reset',
    GRATITUDE: 'gratitude',
    QUIZ: 'quiz',
    EXTERNAL_HELP: 'external_help',
    GAMES: 'games',
    CONTACTS: 'contacts',
    HELPLINE: 'helpline',
  },
  EMOTIONS: ['calm', 'neutral', 'tired', 'stressed', 'anxious', 'overwhelmed', 'sad', 'happy', 'angry', 'fear'],
  LANGUAGES: [
    { code: 'en', label: 'English', native: 'English' },
    { code: 'hi', label: 'Hindi', native: 'हिन्दी' },
    { code: 'ta', label: 'Tamil', native: 'தமிழ்' },
    { code: 'te', label: 'Telugu', native: 'తెలుగు' },
    { code: 'kn', label: 'Kannada', native: 'ಕನ್ನಡ' },
    { code: 'ml', label: 'Malayalam', native: 'മലയാളം' },
    { code: 'bn', label: 'Bengali', native: 'বাংলা' },
    { code: 'mr', label: 'Marathi', native: 'मराठी' },
    { code: 'gu', label: 'Gujarati', native: 'ગુજરાતી' },
    { code: 'pa', label: 'Punjabi', native: 'ਪੰਜਾਬੀ' },
    { code: 'ur', label: 'Urdu', native: 'اردو' },
    { code: 'or', label: 'Odia', native: 'ଓଡ଼ିଆ' },
    { code: 'as', label: 'Assamese', native: 'অসমীয়া' },
  ],
  HELPLINES_IN: [
    { name: 'KIRAN Helpline', phone: '1800-599-0019', desc: 'Govt. of India mental health', region: 'IN' },
    { name: 'Vandrevala Foundation', phone: '1860-2662-345', desc: '24/7 free counselling', region: 'IN' },
    { name: 'iCall', phone: '9152987821', desc: 'Counselling support (Mon–Sat)', region: 'IN' },
    { name: 'AASRA', phone: '9820466726', desc: '24/7 crisis intervention', region: 'IN' },
    { name: 'Snehi', phone: '9582208181', desc: 'Suicide prevention helpline', region: 'IN' },
    { name: 'NIMHANS', phone: '080-46110007', desc: 'National mental health helpline', region: 'IN' },
  ],
  WS_EVENTS: {
    CONNECT: 'connection',
    DISCONNECT: 'disconnect',
    JOIN: 'session:join',
    LEAVE: 'session:leave',
    USER_MESSAGE: 'chat:user_message',
    AIRA_REPLY: 'chat:aira_reply',
    STRESS_UPDATE: 'stress:update',
    EMOTION_UPDATE: 'emotion:update',
    SOS_TRIGGER: 'sos:trigger',
    SOS_RESPONSE: 'sos:response',
    NOTIFICATION: 'notification',
  },
};
